Update __init__.py
New python 3 documentation requires import urllib.request on line 13, otherwise error on line 95 will occur returning; json_page = urllib.request.urlopen(url_page, timeout=10)
AttributeError: module 'urllib' has no attribute 'request'